@startuml New Goal Sequence Diagram
participant User
participant Browser
participant Web_Server
participant Database

User -> Browser: create goal button clicked
Browser -> Web_Server: HTTP GET /users/new_goal
Web_Server -> Browser: New Goal Form
User -> Browser: Submit Form Pt1 {goal, goal due date}
Browser -> Web_Server: HTTP POST /users/new_goal?pt2
Web_Server -> Database: store username, goal, goal date
Web_Server -> Browser: New Goal Form Pt 2
User -> Browser: Submit Form Pt2 {goal why, specific outcome}
Browser -> Web_Server: HTTP POST /users/new_goal?pt3
Web_Server -> Database: store goal why, specific outcome
Web_Server -> Browser: New Goal Form Pt 3
User -> Browser: Submit Form Pt3 {milestones, milestone due date, milestone rewards}
Browser -> Web_Server: HTTP POST /users/new_goal?pt2
Web_Server -> Database: store milestones, milestone due date, milestone rewards : complete goal
Web_Server -> Browser: Flash: Goal Saved! Redirect: /users/profile

@enduml